version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: transactions_service
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    networks:
      - app-network
    tty: true
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: ["./start.sh"]
    env_file: .env
    ports:
      - 3001:3000
    tty: true
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    depends_on:
      - db


networks:
  app-network:
    driver: bridge
