version: "3"

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: transactions_service
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
